### ISSUE TITLE
Problem, entering a measurement after waiting some time (session problem?)

### ISSUE THREAD

**Issue by StefanSchubert** [StefanSchubert/sabi#93]
Web log shows:

```
Mai 15 19:27:37 Shangri-La sabi-webclient.jar[579]: 15-05-2021 19:27:37.138 [http-nio-8088-exec-7] ERROR de.bluewhale.sabi.webclient.apigateway.MeasurementServiceImpl.save
Mai 15 19:27:37 Shangri-La sabi-webclient.jar[579]: 15-05-2021 19:27:37.165 [http-nio-8088-exec-7] ERROR de.bluewhale.sabi.webclient.controller.MeasurementListView.save - C
Mai 15 19:27:37 Shangri-La sabi-webclient.jar[579]: de.bluewhale.sabi.exception.BusinessException: null
Mai 15 19:27:37 Shangri-La sabi-webclient.jar[579]:         at de.bluewhale.sabi.webclient.apigateway.MeasurementServiceImpl.save(MeasurementServiceImpl.java:229)
Mai 15 19:27:37 Shangri-La sabi-webclient.jar[579]:         at de.bluewhale.sabi.webclient.apigateway.MeasurementServiceImpl$$FastClassBySpringCGLIB$$f501b1e1.invoke(<gener
Mai 15 19:27:37 Shangri-La sabi-webclient.jar[579]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
Mai

```

Backend log shows nothing.

**Comment by StefanSchubert** [comment]
Couldn't reproduce. I synced nginx SSL session with sabis session duration and prolonged it to 20min. This should be sufficient between subsequent measurments. Maybe that's it. Raise the issue again, if it still occours during real measurement sessions.

**Comment by StefanSchubert** [comment]
It reoccured and it looks like that the backend token is just invalid. while the frontend session may stay a little longer, the uses backend token as been issued at login time. from then 20 minutes valid. It looks like that we forgot a renewal process or we need to extend the backend tokens TTL.
